# Project Analysis

In [1]:
# ! pip install calitp_data_analysis

In [2]:
# ! pip install "camelot-py[base]"

In [3]:
# ! pip install pdfplumber

In [4]:
# ! pip install tabula-py

In [5]:
import pandas as pd 

# from calitp_data_analysis.sql import to_snakecase
import numpy as np

import os
import re

# import camelot
# import pdfplumber
# import tabula

In [6]:
from IPython.display import HTML

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
pd.set_option('display.max_colwidth', None)

In [9]:
GCS_PATH = "gs://calitp-analytics-data/data-analyses/project_analysis/"
GCS_PATH_AGENDAS = "gs://calitp-analytics-data/data-analyses/project_analysis/ctc_meeting_books/"

### Attempting with Python Package PDF Readers

#### Camelot

In [10]:
# opened_pdf = camelot.read_pdf(f"./complete-book-1056.pdf", pages = "8,9,10", flavor='stream')

In [11]:
# final = pd.DataFrame()

# for page, pdf_table in enumerate(opened_pdf):           
#         table = opened_pdf[page].df
#         final = pd.concat([final, table], axis=0)

In [12]:
# final

#### PDF Plumber

In [13]:
target_string = "ALLOCATIONS AND SUPPLEMENTAL FUNDS REQUEST"
target_string = "2.5e."

In [14]:
# # with pdfplumber.open(f"./complete-book-1056.pdf") as pdf:

# #     page = pdf.pages[8]
# #     text = page.extract_text()
# #     table = page.extract_table(table_settings={"vertical_strategy": "lines", 
# #                                                "horizontal_strategy": "text", 
# #                                                "snap_tolerance": 4,})
    
# #     df = pd.DataFrame(table, columns=table[0]).T


# with pdfplumber.open("./complete-book-1056.pdf") as pdf:
#     for page in pdf.pages:
#         text = page.extract_text()
        
#         if text and target_string in text:
#             # Split the text at the target string and keep the second part
#             relevant_text = text.split(target_string, 1)[1]
#             print(relevant_text)

In [15]:
# all_tables = page.extract_tables()
# dataframes = [pd.DataFrame(t[1:], columns=t[0]) for t in all_tables if t]

In [16]:
# page = pdf.pages[8]
# im = page.to_image(resolution=150)
# im.reset().debug_tablefinder()

In [17]:
# text

In [18]:
# def find_table_by_text(pdf_path, search_string):
#     with pdfplumber.open(pdf_path) as pdf:
#         for page in pdf.pages:
#             tables = page.extract_tables()
#             for table in tables:
#                 if not table or len(table) < 2:
#                     continue  # Skip empty or single-row tables
                
#                 headers = table[0]
#                 data = table[1:]
                
#                 df = pd.DataFrame(data, columns=headers) 
                
#                 if df.astype(str).apply(lambda x: x.str.contains(search_string, case=False, na=False)).any().any():
#                     return df
#     return None

#### Tabula

In [19]:
# dfs = tabula.read_pdf("complete-book-1056.pdf", pages='all')

In [20]:
#### Tablua doesnt run- needs other packages

### Reading in Manual Attempt

In [21]:
ctc_agendas = pd.read_excel(f"{GCS_PATH}2_5e_items.xlsx")

In [22]:
ctc_agendas.columns

Index(['source_pdf', 'meeting', 'reference_number', 'memo_page', 'resolution',
       'subject_phase', 'subject', 'ppno', 'ea', 'county', 'route', 'program',
       'dist_co_rte', 'postmile', 'allocation_amount', 'requested_amounts',
       'prepared_by', 'prepared_division', 'project_description', 'issue'],
      dtype='object')

In [23]:
ctc_agendas.sample(10)

,source_pdf,meeting,reference_number,memo_page,resolution,subject_phase,subject,ppno,ea,county,route,program,dist_co_rte,postmile,allocation_amount,requested_amounts,prepared_by,prepared_division,project_description,issue
43,complete-book-989.pdf,"December 5-6, 2024",2.5e.(6),791,FA-24-36,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 6949/EA 0W800 - FRESNO COUNTY - STATE ROUTE 99,6949,0W800,Fresno,State Route 99,SHOPP,06-Fre-99,21.2/24.4,6750000,NaN,Diana Gomez,District 06 - Director,"Rehabilitate roadway, repair or replace culverts, construct pumping plants, and remove or replace bridges. This is a Construction Manager/General Contractor (CMGC) project. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $6,000,000 in Plans, Specifications, and Estimate (PS&E) and $750,000 in Right of Way (RW) Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Roadway Rehabilitation project on State Route (SR) 99, in Fresno County, to complete the PS&E and RW phases?"
3,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(4),746,FA-24-60,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 2020B/EA 0P910 - ALAMEDA COUNTY - INTERSTATE 680,2020B,0P910,Alameda,Interstate 680,SHOPP,04-Ala-680,NaN,1259000,"$1,400,000 in Capital Outlay Support",Dina El-Tawansy,District 04 - Director,"Scour mitigation, bridge deck rehabilitation, and joint seal replacement. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $1,400,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Bridge Scour project on Interstate 680 (I-680), in Alameda County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
36,complete-book-1061.pdf,"January 30-31, 2025",2.5e.(15),502,"FA-24-57, AMENDING RESOLUTION FA-24-26","ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, ON THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, ON THE STATE HIGHWAY SYSTEM",2323B,NaN,Alameda,NaN,STIP,04-Ala-80,6.4/6.8,4937000,NaN,"James R. Anderson, Chief",Division of Financial Programming,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State Transportation Improvement Program (STIP) I-80/Gilman Interchange Bicycle/Pedestrian Over-crossing and Access Improvements (Phase 2: Interchange) project (PPNO 2323B), on Interstate 80, in Alameda County, to revise the recipient?"
13,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(2),740,FA-25-01,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 5141/EA 0J550 - PLACER COUNTY - INTERSTATE 80,5141,0J550,Placer,Interstate 80,SHOPP,03-Pla-80,NaN,288000,"$288,000 in Capital Outlay Support",Sergio Aceves,District 03 - Director,"Upgrade maintenance station, rehabilitate water system, install electric vehicle chargers, replace sand storage building, relocate fiber network equipment, install closed circuit televisions, and upgrade communication line. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $288,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Maintenance Facilities project on Interstate 80 (I-80), in Placer County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
49,complete-book-989.pdf,"December 5-6, 2026",2.5d.(2),768,FP-24-37,ALLOCATION FOR PROJECT WITH COSTS THAT EXCEED THE\nPROGRAMMED AMOUNT BY MORE THAN 20 PERCENT,ALLOCATION FOR PROJECT WITH COSTS THAT EXCEED THE\nPROGRAMMED AMOUNT BY MORE THAN 20 PERCENT\nPPNO 8053/EA 1A462 – FRESNO COUNTY – STATE ROUTE 180,8053,1A462,Fresno,State Route 180,SHOPP,06-Fre-180,M77.0/R77.7,91000,NaN,Diana Gomez,District 06 – Director,"This project is located on SR 180 near Yokuts Valley, east of Elwood Road. The project will perform oak tree mitigation and replacement planting work for the parent project (EA 1A460/PPNO 7047) which is constructing a two-way left-turn lane (TWLTL), upgrading drainage systems, and installing transportation management system elements.","Should the California Transportation Commission (Commission) approve the California Department of Transportation’s (Department) allocation request for $91,000 for the Project Approval and Environmental Document (PA&ED) Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Safety Improvements project on State Route (SR) 180, in Fresno County, to complete the PA&ED phase?"
18,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(7),751,FA-25-04,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT PPNO 5484/EA 35320 - LOS ANGELES COUNTY - INTERSTATE 405,5484,35320,Los Angeles,Interstate 405,SHOPP,07-LA-405,0.0/12.8,11114000,"$11,114,000 in Construction Capital",Gloria Roberts,District 07 - Director,NaN,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $11,114,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Pavement Preservation project on Interstate 405 (I-405), in Los Angeles County, to re-advertise the construction contract?"
20,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(9),780,FA-25-11,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE PPNO 3005R/EA 0R420 - SAN BERNARDINO COUNTY - INTERSTATE 15,3005R,0R420,San Bernardino,Interstate 15,SHOPP,08-SBd-15,NaN,18400000,"$15,600,000 in Construction Capital | $2,800,000 in Construction Support",Catalino Pining III,District 08 - Director,Construct new maintenance facility (L5758) adjacent to the Southern Regional Laboratory. This project will help keep local highways and freeways in operational condition and reduce maintenance response time. This was a Design-Build project.,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $15,600,000 in Construction Capital and $2,800,000 in Construction Support for the State Highway Operation and Protection Program (SHOPP) Maintenance Facilities project on Interstate 15 (I-15), in San Bernardino County, to complete the construction contract?"
6,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(7),754,FA-24-62,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 6726/EA 0S050 - KERN COUNTY - STATE ROUTE 166,6726,0S050,Kern,State Route 166,SHOPP,06-Ker-166,16.6/18.2,570000,"$570,000 in Capital Outlay Support",Michael Navarro,District 06 - Director,Bridge rehabilitation and seismically retrofit bridge. Supplemental funds are needed to complete PS&E.,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $570,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Bridge Rehabilitation and Replacement project on State Route (SR) 166, in Kern County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
17,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(6),776,FA-25-10,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE PPNO 6034/EA 3311U - VENTURA COUNTY - UNITED STATES HIGHWAY 101 AND STATE ROUTE 23,6034,3311U,Ventura,United States Highway 101 And State Route 23,SHOPP,07-Ven-101,0.2/40.8,2300000,"$2,300,000 in Construction Capital",Gloria Roberts,District 07 - Director,"Upgrade guardrail, end treatments, and bridge connections, construct concrete barrier, add vegetation control under guardrails, and replace dikes to enhance safety and to reduce the number and severity of injuries. Also, construct access trails and Maintenance Vehicle Pullouts, relocate irrigation facilities, install access gates, railings and breakaway post sleeves, and pave gore, narrow, and slope areas to improve worker safety.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $2,300,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Collision Severity Reduction and Roadside Safety Improvements project on United States Highway 101 (US 101) and State Route (SR) 23, in Ventura County, to complete the construction contract?"
11,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(14),774,FA-24-71,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT PPNO 0049T/EA 0G850 - RIVERSIDE COUNTY - INTERSTATE 10,0049T,0G850,Riverside,Interstate 10,SHOPP,08-Riv-10,R71.2/R72.6,4707000,"$4,707,000 in Construction Capital",Catalino Pining III,District 08 - Director,Reconstruct and upgrade eastbound and westbound SRRA facilities and upgrade water and wastewater systems.,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $4,707,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Safety Roadside Rest Area (SRRA) Rehabilitation project on Interstate 10 (I-10), in Riverside County, to award the construction contract?"

In [24]:
ctc_agendas['prepared_division'] = ctc_agendas['prepared_division'].str.replace('–', '-', regex=False)

In [25]:
### identified another column that has all district numbers
# ctc_agendas['district'] = np.where(
#     ctc_agendas['prepared_division'].str.contains('-'), 
#     ctc_agendas['prepared_division'].str.split(' - ').str[0], 
#     'Not Specified')

In [26]:
ctc_agendas['district'] = ctc_agendas['dist_co_rte'].str[:2]

In [27]:
ctc_agendas.district.value_counts()

07    8
01    6
05    6
10    6
04    5
06    5
03    4
08    3
09    2
12    2
11    2
02    1
Name: district, dtype: int64

In [28]:
ctc_agendas.source_pdf.value_counts()

complete-book-1061.pdf    13
complete-book-1056.pdf    12
complete-book-1059.pdf    12
complete-book-989.pdf     11
complete-book-1139.pdf     2
Name: source_pdf, dtype: int64

In [29]:
# (ctc_agendas>>filter(_.district=="Not Specified")).prepared_division.value_counts()

In [30]:
# (ctc_agendas>>filter(_.district=="Not Specified"))

In [31]:
ctc_agendas.subject_phase.value_counts()

SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE                                                         17
SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT                                       14
SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE                                                        13
SUPPLEMENTAL FUNDS FOR CONSTRUCTION CLOSEOUT PHASE                                                           2
ALLOCATION FOR PROJECT WITH COSTS THAT EXCEED THE\nPROGRAMMED AMOUNT BY MORE THAN 20 PERCENT                 2
ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, ON THE STATE HIGHWAY SYSTEM     1
ALLOCATION AMENDMENT FOR A STATE HIGHWAY OPERATION AND PROTECTION PROGRAM PROJECT                            1
Name: subject_phase, dtype: int64

In [32]:
ctc_agendas['route_all'] = ctc_agendas['dist_co_rte'].str.split('-').str[-1]

In [33]:
ctc_agendas.route_all.value_counts()

5      5
101    4
1      4
15     3
4      2
99     2
84     2
80     2
162    2
405    2
134    2
395    2
10     1
49     1
2      1
299    1
90     1
805    1
88     1
33     1
105    1
680    1
46     1
82     1
9      1
57     1
50     1
156    1
166    1
180    1
Name: route_all, dtype: int64

In [34]:
# ctc_agendas.groupby(['district']).agg({'los_2022_q1': 'mean',

In [35]:
# (ctc_agendas[ctc_agendas['issue'].str.contains("000")])

* some of the text in the `issue` and `requested_amounts` columns are including different fonts and different styling in the values. could be a result of the tool run but need to debug.

In [36]:
ctc_agendas['issue'] = ctc_agendas['issue'].astype("string")

In [37]:
# ctc_agendas.sample(10)

In [38]:
# print(((ctc_agendas[ctc_agendas['issue'].str.contains("6,000,000")]))['issue'].values[0])

In [39]:
full = pd.read_csv(f"{GCS_PATH}ctc_extracted_items.csv")

In [40]:
full.head(1)

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county
0,NaN,2.5f,NaN,NaN,NaN,NaN,NaN,NaN,"December 6-7, 2023",2023-12-06-07,2023,351.0,NaN,NaN,NaN,NaN,"Keith Duncan, Chief",Division of Budgets,SHOPP,NaN,NaN,NaN,NaN,NaN,NaN,2.5f,NaN,NaN,NaN,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,NaN,NaN,allocation_amendment,NaN

In [41]:
# full

In [42]:
len((full[full['ppno'].isna()]))

156

In [43]:
(full[full['ppno'].isna()]).groupby(['meeting_year','base_code']).size()

meeting_year  base_code
2021          2.5b          1
2022          2.5b          1
              2.5h          1
              2.5n          1
2023          2.5b          2
              2.5c          1
              2.5f          1
              2.5n          1
              2.5w          1
              2.8b          5
              2.8c          3
              2.8d          2
              2.8v          2
2024          2.5b          4
              2.5f          3
              2.5s          3
              2.5w          1
              2.8a          1
              2.8b          2
              2.8c          9
              2.8d          8
              2.8v          8
2025          2.5b          7
              2.5c          1
              2.5f          7
              2.5h          2
              2.5n          1
              2.5w          2
              2.8a          9
              2.8b          2
              2.8c         11
              2.8d          9
              2.8v         22
2026          2.5b          5
              2.5e          1
              2.5f          3
              2.5w          1
              2.8a          1
              2.8b          1
              2.8c          7
              2.8d          1
              2.8v          2
dtype: int64

In [44]:
(full[(full['ppno'].isna()) & (full["meeting_year"] == 2025) & (full["base_code"] == "2.8v")]).groupby(['meeting_date','memo_page_start']).size()

meeting_date   memo_page_start
2025-01-30-31  1028.0             1
               1031.0             1
               1036.0             1
2025-03-20-21  1034.0             1
               1037.0             1
2025-05-15-16  1374.0             1
               1377.0             1
               1382.0             1
               1387.0             1
2025-06-26-27  1653.0             1
               1669.0             1
               1676.0             1
               1682.0             1
               1687.0             1
2025-08-14-15  1030.0             1
               1046.0             1
               1048.0             1
2025-10-16-17  1488.0             1
               1491.0             1
               1494.0             1
               1504.0             1
2025-12-04-05  1844.0             1
dtype: int64

In [45]:
# (full[(full["meeting_year"] == 2025) & (full["base_code"] == "2.8v")]).groupby('ppno').size()

In [46]:
### example of project that has multiple entries, one with no PPNO number since the script pulled just the second page of a memo, rather than the first that had the information on it. Check Page 1652 on the CTC meeting book 2025-06-26-2

full[full["ppno"] == "3230"]

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county
618,6566000.0,2.8v,San Joaquin,Support,NaN,10.0,1C960,04/30/2025 10/31/2025,NaN,2025-06-26-27,2025,1654.0,6 Months 12 Months,CON/CON Support,NaN,3230,NaN,NaN,SHOPP,NaN,NaN,NaN,1.0,NaN,"SHOPP Transportation Management Systems project The Department requests an additional 6 months, from 6 months to 12 months, for the period of project completion for the Construction (CON) phase of the SHOPP Transportation Management Systems project. The Department has experienced unexpected delays in completing construction. The project is located on State Route (SR) 120, in and near Manteca and Lathrop, from Interstate 5 to SR 99. The project proposes to install fiber optic cable as part of the Department’s Transportation Management System. Initially, the project received a 6-month extension to resolve a damaged fiber optic line. The contract was awarded in October 2021 and the 36-month deadline to complete Construction Contract Acceptance (CCA) was October 31, 2024. During construction, the contractor ran over and damaged a fiber optic cable while working on the site. This damaged fiber optic line is required to be fully functional with the newly installed project elements. Based on communication with the Contractor and Construction Support team, replacement order and installation of the damaged line was anticipated to take an additional three to six months. The remaining project scope was to be completed concurrently. Since then, the project experienced further delays in late March 2025, primarily due to the absence of factory test results for the fiber optic cables. These test results are essential for evaluating the performance of the installed fiber optic system as part of the project’s acceptance process. The contractor contacted the fiber optic supplier to request a copy of the factory test results. Unfortunately, the supplier was unable to provide them, as the records were no longer available. After discussions between the Department and the contractor on how to proceed, the testing and inspection will rely on the delivered test results in lieu of the factory test results. The",2.8v.(1),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,NaN,NaN,time_extension,NaN

In [47]:
(full[(full['ppno'].isna())]).groupby(['meeting_date', 'source']).size()

meeting_date      source
2023-12-06-07     pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf            16
2024-05-16-17     pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf            18
2024-08-15-16     pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf             9
2024-12-05-06     pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf             11
2025-01-30-31     pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf             7
2025-03-20-21     pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf             9
2025-05-15-16     pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf            13
2025-06-26-27     pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf            17
2025-08-14-15     pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf             6
2025-10-16-17     pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf     9
2025-12-04-05     pdfs/2025/2025-12-04-05/2025-12-04-05_complete-book-1858.pdf             5
2026-01-29-30     pdfs/2026/2026-01-29-30/2026-01-29-30_complete-book-1139.pdf             6
2026-03-19-20     pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf             8
2026-05-14-15     pdfs/2026/2026-05-14-15/2026-05-14-15_complete-book-959.pdf              8
June 26-27, 2025  pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf        7
June 28-29, 2023  pdfs/2023/2023-06-28-29/2023-06-28-29_tab-112-2-5n-att-a11y.pdf          1
                  pdfs/2023/2023-06-28-29/2023-06-28-29_tab-125-2-5c10-a11y.pdf            1
June 29-30, 2022  pdfs/2022/2022-06-29-30-22/2022-06-29-30-22_tab-89-2-5h.pdf              1
                  pdfs/2022/2022-06-29-30-22/2022-06-29-30-22_tab-94-2-5n-a11y.pdf         1
June 30, 2021     pdfs/2021/unknown_date/tab-5-2-5b2-combined-a11y.pdf                     1
May 16-17, 2024   pdfs/2024/2024-05-16-17/2024-05-16-17_tab-138-2-8v5-lett.pdf             1
May 18-19, 2022   pdfs/2022/2022-05-18-19-22/2022-05-18-19-22_tab-83-2-5b3-a11y.pdf        1
dtype: int64

In [48]:
len(full)

1274

In [49]:
(full[(full['ppno'].isna()) & (full['meeting_date']=='June 26-27, 2025')])

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county
1259,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1260,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1261,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1262,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1263,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1266,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN
1267,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN

In [50]:
ppno_null = (full[(full['ppno'].isna())])

In [51]:
# ppno_null.to_csv('ppno_null_checks.csv')

In [71]:
ppno_counts = (full.groupby(['ppno', 'source']).size()).reset_index()

In [77]:
ppno_counts.columns

Index(['ppno', 'source', 0], dtype='object')

In [78]:
ppno_counts = ppno_counts.rename(columns={0:"counts"})

In [84]:
(ppno_counts[ppno_counts['counts']>1]).sort_values('counts')

,ppno,source,counts
2,0044D,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
471,3011R,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
489,3020J,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
490,3020Y,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,2
533,3203,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
538,3215,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,2
545,3276,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
553,3433,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
558,3439,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
616,4353,pdfs/2026/2026-05-14-15/2026-05-14-15_complete-book-959.pdf,2
643,4630,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,2
658,4704,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
678,4785,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,2
720,5059,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
732,5131,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
742,5185,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
763,5370,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
784,5484,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
793,5511,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
807,5625,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
844,6041,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
876,6406,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
923,6960,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
936,6985,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
459,3008C,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
942,7005,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
456,3006G,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,2
437,2992,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
3,0049T,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
33,0226J,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
128,1276,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
133,1302,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,2
243,2024D,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
245,2026H,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
248,2027J,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,2
277,2323B,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
453,3005R,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
312,2448,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,2
352,2627,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
282,2349,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
363,2645,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
369,2649,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
378,2655,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
388,2679X,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
400,2776,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
410,2850,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
416,2859C,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
418,2904,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
360,2641,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
998,CP033,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
574,3546,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,3
703,4998,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,3
373,2653,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,3
241,2022G,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,3
105,0999C,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,3
52,0361M,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,4

In [67]:
full[full["ppno"] == "5226"]

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county
64,6394000.0,2.8v,Los Angeles,Support,NaN,7.0,33860,11/30/2023 03/31/2024,NaN,2023-12-06-07,2023,1327.0,9 Months 13 Months,Construction,NaN,5226,NaN,NaN,SHOPP,NaN,NaN,NaN,1.0,NaN,"The Department is requesting an additional 4 months, from 9 months to 13 months, for the period of contract award for the Construction (CON) phase of the SHOPP Mobility project. The Department has experienced unexpected delays in awarding this project. This project is located on State Route (SR) 91, in the Cities of Los Angeles, Carson, Compton, Long Beach, Bellflower, Cerritos, and Artesia, from SR 110 to Orange County line; also on SR 2, Interstate 5 (I-5), and I-405. The project intends to upgrade the existing transportation management system elements to improve traffic monitoring, data transmission, and network connectivity, including the various communication hubs on SR 2, I-5, and I-405. This project will help to better manage traffic and keep the system network operating at a high level of reliability. Initially, the Department held bid opening on October 25, 2022, and received only two bids. Both bids came in higher than the Engineer's Estimate (EE). However, the first lowest bidder was deemed non-responsive for not meeting the Disadvantaged Business Enterprise (DBE) goals. The second lowest bid came in 125 percent above the EE. In March 2023, the Commission approved a 9-month project development expenditure time extension to accommodate the delays in awarding the project due to the need to investigate the reasons that prevented the lowest bidder from meeting the DBE goals since the second bid was determined not feasible as it is not competitive with the first bid. The lowest bidder elected not to participate in the Department's Award Committee hearing. Therefore, the committee rejected the lowest bidder, and the Department elected to re-package and re-advertise the project.",2.8v.(2),NaN,NaN,NaN,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,NaN,NaN,time_extension,NaN