# Project Analysis

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd 

import numpy as np

import os
import re

import altair as alt

from calitp_data_analysis.sql import to_snakecase
from calitp_data_analysis import calitp_color_palette as cp

from IPython.display import Markdown, HTML, display_html, display
from IPython.core.display import display

In [3]:
from IPython.display import HTML

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
pd.set_option('display.max_colwidth', None)

In [6]:
GCS_PATH = "gs://calitp-analytics-data/data-analyses/project_analysis/"
GCS_PATH_AGENDAS = "gs://calitp-analytics-data/data-analyses/project_analysis/ctc_meeting_books/"

In [7]:
### read in data
full = pd.read_csv(f"{GCS_PATH}ctc_extracted_items_updated.csv")

In [8]:
# full

In [9]:
display(HTML(f'<h2>Summary</h2>'))

In [10]:
 display(HTML(f"Over the last six years, there have been <strong>{len(full)}</strong> items that have appeared in CTC meeting books"))

In [11]:
(full.type.value_counts().reset_index()).rename(columns={"index":"Item Type", "program":"Number of Items"})

              Item Type  type
0        time_extension   857
1  allocation_amendment   411

In [12]:
display(HTML(f'<h3>Item Types</h3>'))

In [13]:
# ((full.groupby(['meeting_year', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items"})

In [14]:
chart = ((alt.Chart(((full.groupby(['meeting_year', 'type']).size()).reset_index().rename(columns={0:"Number of Items"})))
            .mark_bar()
            .encode(
                x=alt.X("type:O", title="Item Type"),
                 y=alt.Y('Number of Items'),
                color=alt.Color("type", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                column='meeting_year'
         )
          .properties(title="Number of Related Items in Analyses", 
                      width=100,
                      height=300)))

In [15]:
chart

alt.Chart(...)

In [16]:
display(HTML(f'<strong>Count of Item Types</strong>'))

In [17]:
(full.meeting_year.value_counts()).reset_index().rename(columns={"index":"Year", "meeting_year":"Number of Items"})

   Year  Number of Items
0  2025              570
1  2024              213
2  2020              175
3  2026              154
4  2023               87
5  2022               46
6  2021               25

In [18]:
display(HTML(f'<strong>Count of Item Types by Subtype</strong>'))

In [19]:
((full.base_code.value_counts()).reset_index()).rename(columns={"index":"Item Code", "base_code":"Number of Items"})

   Item Code  Number of Items
0       2.8a              245
1       2.5e              190
2       2.8c              160
3       2.8d              152
4       2.8v              140
5       2.8b              135
6       2.5d               75
7       2.5s               48
8       2.5b               36
9       2.8i               27
10      2.5c               22
11      2.5w               20
12      2.5f               14
13      2.5h                3
14      2.5n                3

In [20]:
# alt.Chart((((full.groupby(['meeting_year', 'base_code']).size()).reset_index()).rename(columns=({0:"number_of_items"})))).mark_bar(size=70).encode(
#     x=alt.X('meeting_year', title="Meeting Year"),
#     y=alt.Y('number_of_items',),
#     color=alt.Color('base_code')
# ).properties(title="Item Types in Agendas",
#         width=700,
#         height=500)

In [21]:
full.district.value_counts()

4.0     84
7.0     63
10.0    59
11.0    42
5.0     42
12.0    33
3.0     27
8.0     26
1.0     24
6.0     21
9.0     10
2.0      9
75.0     8
15.0     4
50.0     4
20.0     3
80.0     3
13.0     2
18.0     2
14.0     1
95.0     1
88.0     1
99.0     1
62.0     1
38.0     1
70.0     1
79.0     1
74.0     1
60.0     1
39.0     1
17.0     1
92.0     1
85.0     1
24.0     1
Name: district, dtype: int64

In [22]:
district = full[full['district']<=12]

In [23]:
# ((district.groupby(['district', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items", "type":"Item Type", "district":"District"})

In [24]:
chart = ((alt.Chart((((district.groupby(['district', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items", "type":"Item Type", "district":"District"})))
            .mark_bar(size=50)
            .encode(
                x=alt.X("District:Q", title="Caltrans District"),
                 y=alt.Y('Number of Items:Q', title="Number of Items"),
                color=alt.Color("Item Type", title="Caltrans District", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)
                ))
          .properties(title="Number of Items in Analyses by District",
        width=800,
        height=300)))
chart

alt.Chart(...)

In [25]:
full['county'] = full['county'].str.replace(' County', '', regex=False)

In [26]:
chart = ((alt.Chart((full.county.value_counts().reset_index()))
            .mark_bar(size=8)
            .encode(
                x=alt.X("index", title="County"),
                 y=alt.Y('county', title="Number of items"),
                color=alt.Color("index", title="County", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Number of Items in Analyses by County",
        width=1100,
        height=300)))
chart

alt.Chart(...)

In [27]:
display(HTML(f'<strong>Count of Program Types</strong>'))

In [28]:
(full.program.value_counts().reset_index()).rename(columns={"index":"Program", "program":"Number of Items"})

  Program  Number of Items
0   SHOPP              612
1    STIP               82
2    TCEP               28
3     ATP               22
4     LPP               22
5    SCCP                1

In [29]:
# full.sample()

In [30]:
# ((full.groupby(['meeting_year', 'base_code']).size()).reset_index()).rename(columns=({0:"number_of_items"}))

In [31]:
full['prepared_division'] = full['prepared_division'].str.replace(' â€“', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace('-', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace(' (Acting)', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace('  ', ' ', regex=False)

In [32]:
# full.prepared_division.value_counts()

In [33]:
display(HTML(f'<strong>Types of Items Presented by the Division of Local Assistance </strong>'))

In [34]:
((full[full['prepared_division']=="Division of Local Assistance"]).base_code.value_counts().reset_index()).rename(columns={"index":"Item Code", "base_code":"Number of Items"})

  Item Code  Number of Items
0      2.5w               14
1      2.5s                8
2      2.5c                6
3      2.8b                2
4      2.8c                1

In [35]:
display(HTML(f'<strong>Types of Items Presented by the Division of Local Assistance </strong>'))

In [36]:
(full[full['prepared_division']=="Division of Local Assistance"]).type.value_counts()

allocation_amendment    28
time_extension           3
Name: type, dtype: int64

In [37]:
display(HTML(f'<strong>Types of items in the LPP Program</strong>'))

In [38]:
(full[full['program']=="LPP"]).type.value_counts()

allocation_amendment    22
Name: type, dtype: int64

In [39]:
# full.columns

In [40]:
display(HTML(f'<h3>Allocation Amendments</h3>'))

In [41]:
full['allocation_amount'] = full['allocation_amount'].str.replace(',', '', regex=False)

In [42]:
amounts = (full[(full['type']=="allocation_amendment") & (full["allocation_amount"].notna())])

In [43]:
amounts['allocation_amount'] = amounts['allocation_amount'].astype(int)

In [44]:
# amounts.groupby('meeting_year').allocation_amount.mean().reset_index()

In [45]:
chart = ((alt.Chart((amounts.groupby('meeting_year').allocation_amount.mean().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('allocation_amount', title="Allocation Amount"),
                color=alt.Color("meeting_year", title="Year", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Average Allocation Amendment Amount by Year",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [46]:
# amounts.groupby(['meeting_year', 'program']).allocation_amount.sum().reset_index()

In [47]:
chart = ((alt.Chart((amounts.groupby(['meeting_year', 'program']).allocation_amount.sum().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('allocation_amount', title="Allocation Amount"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),

                )
          .properties(title="Sum Allocations Amendment Amount by Program",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [49]:
# full[full['']]

In [51]:
# (full[full['reason_for_cost_increase']]).str.contains("inflation")

In [53]:
extension = (full[(full['type']=="time_extension")])

In [54]:
# len(extension)

In [55]:
full.columns

Index(['allocation_amount', 'base_code', 'county', 'department_recommendation',
       'dist_co_rte', 'district', 'ea', 'extended_deadline', 'meeting',
       'meeting_date', 'meeting_year', 'memo_page_start', 'months_requested',
       'phase', 'postmile', 'ppno', 'prepared_by', 'prepared_division',
       'program', 'project_description', 'project_id', 'project_name',
       'project_number', 'reason_for_cost_increase',
       'reason_for_time_extension', 'reference_code', 'requested_amounts',
       'resolution', 'route', 'source', 'subject', 'subject_phase', 'type',
       'vote_county', 'Unnamed: 34'],
      dtype='object')

In [56]:
extension.months_requested.value_counts()

12 Months              111
20 Months               63
6 Months                56
3 Months                44
4 Months                38
                      ...
15 Months 20 Months      1
25 Months 29 Months      1
3 Months 37 Months       1
20 Months 33 Months      1
92 Months                1
Name: months_requested, Length: 179, dtype: int64

In [57]:
# extension['months_requested_int'] = np.where(
#     extension['months_requested'].str.len() < 10, 
#     extension['months_requested'].str.split().str[0], 
#     extension['months_requested']
# )

In [58]:
# len(extension[extension["months_requested"].isna()])

In [59]:
extension['months_requested_latest'] = extension['months_requested'].str.split().str[-2]

In [60]:
# (extension[extension["months_requested_latest"].isna()]).months_requested.value_counts()

In [61]:
# extension.months_requested_latest.value_counts()

In [62]:
extension['months_requested_latest'] = extension['months_requested_latest'].fillna(extension['months_requested'])

In [63]:
# (extension[~extension["months_requested"].isna()]).sample(10)

In [64]:
extension_months = (extension[~extension["months_requested_latest"].isna()])

In [65]:
extension_months['months_requested_latest'] = extension_months['months_requested_latest'].astype(int)

In [66]:
(extension_months.groupby('meeting_year').months_requested_latest.mean().reset_index())

   meeting_year  months_requested_latest
0          2020                36.188976
1          2021                 9.750000
2          2022                25.333333
3          2023                11.500000
4          2024                11.401961
5          2025                11.953333
6          2026                15.093750

In [67]:
chart = ((alt.Chart((extension_months.groupby('meeting_year').months_requested_latest.mean().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Average Extension Months Requested"),
                color=alt.Color("meeting_year", title="Year", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Average Number of Months Extension Requested by Year",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [68]:
(extension_months.groupby(['meeting_year','program']).months_requested_latest.sum().reset_index())

    meeting_year program  months_requested_latest
0           2021   SHOPP                       39
1           2022   SHOPP                       76
2           2022    STIP                       96
3           2023     ATP                       36
4           2023    SCCP                        5
5           2023   SHOPP                      250
6           2023    STIP                       44
7           2024   SHOPP                      598
8           2024    STIP                       32
9           2025   SHOPP                     1537
10          2025    STIP                      335
11          2026   SHOPP                      329
12          2026    STIP                       84

In [69]:
chart = ((alt.Chart((extension_months.groupby(['meeting_year','program']).months_requested_latest.sum().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),

                )
          .properties(title="Total Extension Months by Program",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [72]:
chart = ((alt.Chart((extension_months.groupby(['meeting_year', 'district', 'program']).months_requested_latest.sum().reset_index()))
            .mark_bar()
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                column='district'
                )
          .properties(title="Total Extension Months by Program",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [70]:
chart = ((alt.Chart((extension_months.groupby('county').months_requested_latest.sum().reset_index()))
            .mark_bar()
            .encode(
                x=alt.X("county", title="County"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("county", title="County", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                )
          .properties(title="Total Extension Months by County",
        width=1100,
        # height=300
                     )))
chart

alt.Chart(...)

In [ ]:
# full.groupby(['type', 'base_code']).size()

In [77]:
n_types_ppno = (full.groupby(['ppno']).type.nunique().reset_index())

In [79]:
n_types_ppno[n_types_ppno['type']>1]

      ppno  type
1    0044D     2
2    0049T     2
16   0100V     2
22   0226J     2
29   0298F     2
..     ...   ...
733   7031     2
738   7072     2
740  7088A     2
757    886     2
817  LP003     2

[117 rows x 2 columns]

In [80]:
full[full['ppno']=="0044D"]

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county,Unnamed: 34
515,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025-06-26-27,2025,686.0,NaN,NaN,NaN,0044D,"James R. Anderson, Chief",Division of Financial Programming,LPP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State-Administered multi-funded State Transportation Improvement Program (STIP), Senate Bill 1 (SB 1) Local Partnership Program (LPP) (Competitive and Formulaic) Oakland Alameda Access Project (PPNO 0044D), on the State Highway System, in Alameda County, to revise the post miles?",NaN,2.5s.(6),NaN,"FP-24-93, AMENDING RESOLUTION FP-24-46",NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,"ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED MULTI-FUNDED STATE TRANSPORTATION IMPROVEMENT PROGRAM, SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (COMPETITIVE AND FORMULAIC) PROJECT, ON THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED MULTI-FUNDED STATE TRANSPORTATION IMPROVEMENT PROGRAM, SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (COMPETITIVE AND FORMULAIC) PROJECT, ON THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN,NaN
573,67625000,2.8b,Alameda,Support,NaN,NaN,0G360,3/31/2026,NaN,2025-06-26-27,2025,1547.0,9 Months,Construction,NaN,0044D,NaN,NaN,STIP,NaN,NaN,NaN,1.0,NaN,"The Department requests a 9-month time extension for the period of contract award for the Construction (CON) phase of the Oakland Alameda Access Project. The Department has experienced delays in awarding the project. This project is located on State Route (SR) 260 and Interstate 880 (I-880), between 5th Avenue Overhead and 5th and 6th Street Viaduct within the cities of Oakland and Alameda in Alameda County. The project will improve access along I-880 and in and around the Webster and Posey Tubes, downtown Oakland, and the City of Alameda. Proposed improvements also include implementation of follow-up landscaping work to restore removed vegetation required by the highway improvements. The project achieved Ready to List (RTL) in October 2024 and was initially scheduled to advertise in January 2025, with bids opening in February 2025. However, due to delays related to updating the RTL package and associated coordination efforts, the advertisement occurred in April 2025, and the bid opening was revised to October 2025. The RTL package required updates to comply with the newly issued 2024 Department Construction Contract Standards, released on October 21, 2024. The project includes numerous plan sheets, specifications, and technical reports. Updating these documents to reflect new standards required extensive review by multiple functional units within the Department. Additionally, the project involves significant improvements to local streets within the jurisdiction of the cities of Oakland and Alameda, which will be responsible for maintaining these improvements. As a result, the updated Plans, Specifications, and Estimate (PS&E) package also needed review and approval from the cities. Because the cities follow American Public Works Association specifications, incorporating local design elements into the Departmentâ€™s contract documents necessitated the development and inclusion of several non-standard special provisions. This added another layer of review, approval, and coordination between the Department and the cities. The need to update the RTL package for the new standards and the extensive coordination with the local agencies contributed to a 4-month delay in the project schedule, pushing advertisement to April 2025. Due to the projectâ€™s size and complexity, additional time is being requested to allow for any unforeseen issues with the advertisement, bidder inquiries, possible addenda, and bid protests that may arise. Therefore, the Department is requesting a 9-month time extension for the period of contract award for the CON phase from June 30, 2025 to March 31, 2026.",2.8b.(3),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,NaN,NaN,time_extension,NaN,NaN