# Project Analysis

In [1]:
# ! pip install calitp_data_analysis

In [2]:
# ! pip install "camelot-py[base]"

In [3]:
# ! pip install pdfplumber

In [4]:
# ! pip install tabula-py

In [5]:
import pandas as pd 

# from calitp_data_analysis.sql import to_snakecase
import numpy as np

import os
import re

# import camelot
# import pdfplumber
# import tabula

In [6]:
from IPython.display import HTML

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
pd.set_option('display.max_colwidth', None)

In [9]:
GCS_PATH = "gs://calitp-analytics-data/data-analyses/project_analysis/"
GCS_PATH_AGENDAS = "gs://calitp-analytics-data/data-analyses/project_analysis/ctc_meeting_books/"

### Attempting with Python Package PDF Readers

#### Camelot

In [10]:
# opened_pdf = camelot.read_pdf(f"./complete-book-1056.pdf", pages = "8,9,10", flavor='stream')

In [11]:
# final = pd.DataFrame()

# for page, pdf_table in enumerate(opened_pdf):           
#         table = opened_pdf[page].df
#         final = pd.concat([final, table], axis=0)

In [12]:
# final

#### PDF Plumber

In [13]:
target_string = "ALLOCATIONS AND SUPPLEMENTAL FUNDS REQUEST"
target_string = "2.5e."

In [14]:
# # with pdfplumber.open(f"./complete-book-1056.pdf") as pdf:

# #     page = pdf.pages[8]
# #     text = page.extract_text()
# #     table = page.extract_table(table_settings={"vertical_strategy": "lines", 
# #                                                "horizontal_strategy": "text", 
# #                                                "snap_tolerance": 4,})
    
# #     df = pd.DataFrame(table, columns=table[0]).T


# with pdfplumber.open("./complete-book-1056.pdf") as pdf:
#     for page in pdf.pages:
#         text = page.extract_text()
        
#         if text and target_string in text:
#             # Split the text at the target string and keep the second part
#             relevant_text = text.split(target_string, 1)[1]
#             print(relevant_text)

In [15]:
# all_tables = page.extract_tables()
# dataframes = [pd.DataFrame(t[1:], columns=t[0]) for t in all_tables if t]

In [16]:
# page = pdf.pages[8]
# im = page.to_image(resolution=150)
# im.reset().debug_tablefinder()

In [17]:
# text

In [18]:
# def find_table_by_text(pdf_path, search_string):
#     with pdfplumber.open(pdf_path) as pdf:
#         for page in pdf.pages:
#             tables = page.extract_tables()
#             for table in tables:
#                 if not table or len(table) < 2:
#                     continue  # Skip empty or single-row tables
                
#                 headers = table[0]
#                 data = table[1:]
                
#                 df = pd.DataFrame(data, columns=headers) 
                
#                 if df.astype(str).apply(lambda x: x.str.contains(search_string, case=False, na=False)).any().any():
#                     return df
#     return None

#### Tabula

In [19]:
# dfs = tabula.read_pdf("complete-book-1056.pdf", pages='all')

In [20]:
#### Tablua doesnt run- needs other packages

### Reading in Manual Attempt

In [21]:
ctc_agendas = pd.read_excel(f"{GCS_PATH}2_5e_items.xlsx")

In [22]:
ctc_agendas.columns

Index(['source_pdf', 'meeting', 'reference_number', 'memo_page', 'resolution',
       'subject_phase', 'subject', 'ppno', 'ea', 'county', 'route', 'program',
       'dist_co_rte', 'postmile', 'allocation_amount', 'requested_amounts',
       'prepared_by', 'prepared_division', 'project_description', 'issue'],
      dtype='object')

In [23]:
ctc_agendas.sample(10)

,source_pdf,meeting,reference_number,memo_page,resolution,subject_phase,subject,ppno,ea,county,route,program,dist_co_rte,postmile,allocation_amount,requested_amounts,prepared_by,prepared_division,project_description,issue
47,complete-book-989.pdf,"December 5-6, 2024",2.5e.(11),668,"FA-24-42, AMENDING RESOLUTION FA-24-23",ALLOCATION AMENDMENT FOR A STATE HIGHWAY OPERATION AND PROTECTION PROGRAM PROJECT,ALLOCATION AMENDMENT FOR A STATE HIGHWAY OPERATION AND PROTECTION PROGRAM PROJECT,5184,NaN,Los Angeles,NaN,SHOPP,07-LA-2,2.321/14.200,5770000,NaN,"James R. Anderson, Chief",Division of Financial Programming,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State Highway Operation and Protection Program (SHOPP) Pavement Preservation project (PPNO 5184) on State Route (SR) 2, in Los Angeles County, to correct the Fiscal Year 2017-18 Road Maintenance and Rehabilitation Account (RMRA) revised amount and the total revised amount?"
9,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(11),770,FA-24-67,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT PPNO 2641/EA 36680 - INYO COUNTY - UNITED STATES HIGHWAY 395,2641,36680,Inyo,United States Highway 395,SHOPP,09-Iny-395,117.3/117.9,1761000,"$1,761,000 in Construction Capital",Ryan Dermody,District 09 - Director,"Upgrade and construct new curb ramps and driveways to Americans with Disabilities Act (ADA) standards, refresh striping, relocate signals, and improve pedestrian and bicycle infrastructure.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $1,761,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Americans with Disabilities Act Curb Ramps project on United States Highway (US) 395, in Inyo County, to award the construction contract?"
21,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(10),755,FA-25-05,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT,SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT PPNO 3276/EA 1H360 - SAN JOAQUIN COUNTY - STATE ROUTE 4,3276,1H360,San Joaquin,State Route 4,SHOPP,10-SJ-4,NaN,1101000,"$1,101,000 in Construction Capital",Grace Magsayo,District 10 - Director,"Install walers, place polyester concrete overlay, paint steel bridge, and remove abandoned garage.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $1,101,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Bridge Preventative Maintenance project on State Route (SR) 4, in San Joaquin County, to award the construction contract?"
7,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(9),759,FA-24-64,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 5375/EA 34710 - LOS ANGELES COUNTY - STATE ROUTE 134,5375,34710,Los Angeles,State Route 134,SHOPP,07-LA-134,0.0/R13.3,1259000,"$1,259,000 in Capital Outlay Support",Gloria Roberts,District 07 - Director,"Replace sign structures and sign panels, relocate fiber optic system, upgrade striping, and upgrade guardrail. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $1,259,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Signs and Lighting Rehabilitation project on State Route (SR) 134, in Los Angeles County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
1,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(2),778,FA-24-68,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE,SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE PPNO 6254/EA 0H08U - SACRAMENTO COUNTY - UNITED STATES HIGHWAY 50,6254,0H08U,Sacramento,United States Highway 50,SHOPP,03-Sac-50,NaN,5135000,"$5,135,000 in Construction Capital",Sergio Aceves,District 03 - Director,NaN,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $5,135,000 in Construction Capital for the State Highway Operation and Protection Program (SHOPP) Roadway Rehabilitation and Multimodal Corridor Enhancement project on United States Highway (US) 50, in Sacramento County, to complete the construction contract?"
15,complete-book-1059.pdf,"August 14-15, 2025",2.5e.(4),744,FA-25-02,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 0886/EA 0G660 - SOLANO COUNTY - STATE ROUTE 84,0886,0G660,Solano,State Route 84,SHOPP,04-Sol-84,12.00/12.40,1600000,"$1,600,000 in Capital Outlay Support",David Ambuehl,District 04 - Director (Acting),Replace bridge. Supplemental funds are needed to complete PS&E.,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $1,600,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Bridge Formula Program project on State Route (SR) 84, in Solano County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
43,complete-book-989.pdf,"December 5-6, 2024",2.5e.(6),791,FA-24-36,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 6949/EA 0W800 - FRESNO COUNTY - STATE ROUTE 99,6949,0W800,Fresno,State Route 99,SHOPP,06-Fre-99,21.2/24.4,6750000,NaN,Diana Gomez,District 06 - Director,"Rehabilitate roadway, repair or replace culverts, construct pumping plants, and remove or replace bridges. This is a Construction Manager/General Contractor (CMGC) project. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $6,000,000 in Plans, Specifications, and Estimate (PS&E) and $750,000 in Right of Way (RW) Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Roadway Rehabilitation project on State Route (SR) 99, in Fresno County, to complete the PS&E and RW phases?"
45,complete-book-989.pdf,"December 5-6, 2024",2.5e.(8),800,FA-24-38,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 3133/EA 0X460 - SAN JOAQUIN COUNTY - STATE ROUTE 4 AND INTERSTATE 5,3133,0X460,San Joaquin,State Route 4 And Interstate 5,SHOPP,10-SJ-5,26.1/26.5,48000000,"$48,000,000 in Capital Outlay Support",Grace Magsayo,District 10 - Director,"Bridge rehabilitation to address structural and load carrying capacity deficiencies. This is a Design- Build project. (PA&ED and PS&E Only) As part of this supplemental funds request, the Department will now utilize the Construction Manager/General Contractor in lieu of the Design-Build delivery method. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $48,000,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Bridge Rehabilitation and Replacement project on State Route (SR) 4 and Interstate 5 (I-5), in San Joaquin County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
40,complete-book-989.pdf,"December 5-6, 2024",2.5e.(2),780,FA-24-32,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 2535/EA 0J801 - HUMBOLDT COUNTY - STATE ROUTE 299,2535,0J801,Humboldt,State Route 299,SHOPP,01-Hum-299,R8.0/R9.2,800000,"$800,000 in Capital Outlay Support",Matthew Brady,District 01 - Director,Restore storm damaged roadway by relocating on a new alignment. Supplemental funds are needed to complete PS&E.,"Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $800,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Major Damage (Permanent Restoration) project on State Route (SR) 299, in Humboldt County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"
4,complete-book-1056.pdf,"March 20-21, 2025",2.5e.(5),750,FA-24-61,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE,SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE PPNO 2466/EA 1E030 - SANTA BARBARA COUNTY - STATE ROUTES 1 AND 166,2466,1E030,Santa Barbara,State Routes 1 And 166,SHOPP,05-SB-1,49.2/50.4,950000,"$950,000 in Capital Outlay Support",Scott Eades,District 05 - Director,"Upgrade curb ramps and other facilities to Americans with Disabilities Act (ADA) standards, construct new sidewalks, buffered bike lanes, bulb outs, and install flashing beacons as complete streets elements. Supplemental funds are needed to complete PS&E.","Should the California Transportation Commission (Commission) approve the California Department of Transportation's (Department) request for an additional $950,000 in Capital Outlay Support (COS), for the State Highway Operation and Protection Program (SHOPP) Americans with Disabilities Act Curb Ramps project on State Route (SR) 1 and SR 166, in Santa Barbara County, to complete the Plans, Specifications, and Estimate (PS&E) phase?"

In [24]:
ctc_agendas['prepared_division'] = ctc_agendas['prepared_division'].str.replace('–', '-', regex=False)

In [25]:
### identified another column that has all district numbers
# ctc_agendas['district'] = np.where(
#     ctc_agendas['prepared_division'].str.contains('-'), 
#     ctc_agendas['prepared_division'].str.split(' - ').str[0], 
#     'Not Specified')

In [26]:
ctc_agendas['district'] = ctc_agendas['dist_co_rte'].str[:2]

In [27]:
ctc_agendas.district.value_counts()

07    8
01    6
05    6
10    6
04    5
06    5
03    4
08    3
09    2
12    2
11    2
02    1
Name: district, dtype: int64

In [28]:
ctc_agendas.source_pdf.value_counts()

complete-book-1061.pdf    13
complete-book-1056.pdf    12
complete-book-1059.pdf    12
complete-book-989.pdf     11
complete-book-1139.pdf     2
Name: source_pdf, dtype: int64

In [29]:
# (ctc_agendas>>filter(_.district=="Not Specified")).prepared_division.value_counts()

In [30]:
# (ctc_agendas>>filter(_.district=="Not Specified"))

In [31]:
ctc_agendas.subject_phase.value_counts()

SUPPLEMENTAL FUNDS FOR CAPITAL OUTLAY SUPPORT PHASE                                                         17
SUPPLEMENTAL FUNDS ALLOCATION FOR AWARD OF A PREVIOUSLY VOTED PROJECT                                       14
SUPPLEMENTAL FUNDS FOR CONSTRUCTION COMPLETION PHASE                                                        13
SUPPLEMENTAL FUNDS FOR CONSTRUCTION CLOSEOUT PHASE                                                           2
ALLOCATION FOR PROJECT WITH COSTS THAT EXCEED THE\nPROGRAMMED AMOUNT BY MORE THAN 20 PERCENT                 2
ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, ON THE STATE HIGHWAY SYSTEM     1
ALLOCATION AMENDMENT FOR A STATE HIGHWAY OPERATION AND PROTECTION PROGRAM PROJECT                            1
Name: subject_phase, dtype: int64

In [32]:
ctc_agendas['route_all'] = ctc_agendas['dist_co_rte'].str.split('-').str[-1]

In [33]:
ctc_agendas.route_all.value_counts()

5      5
101    4
1      4
15     3
4      2
99     2
84     2
80     2
162    2
405    2
134    2
395    2
10     1
49     1
2      1
299    1
90     1
805    1
88     1
33     1
105    1
680    1
46     1
82     1
9      1
57     1
50     1
156    1
166    1
180    1
Name: route_all, dtype: int64

In [34]:
# ctc_agendas.groupby(['district']).agg({'los_2022_q1': 'mean',

In [35]:
# (ctc_agendas[ctc_agendas['issue'].str.contains("000")])

* some of the text in the `issue` and `requested_amounts` columns are including different fonts and different styling in the values. could be a result of the tool run but need to debug.

In [36]:
ctc_agendas['issue'] = ctc_agendas['issue'].astype("string")

In [37]:
# ctc_agendas.sample(10)

In [38]:
# print(((ctc_agendas[ctc_agendas['issue'].str.contains("6,000,000")]))['issue'].values[0])

### Read in Extracted Items from the Last Five Years

**Items to Check**
* PPNo numbers not populating
* Incorrect/missing Districts (numbers go until 99)
* Missing counties
* Removing funky rows (2) that have text in all columns
* *

In [39]:
full = pd.read_csv(f"{GCS_PATH}ctc_extracted_items_updated.csv")

In [40]:
full.head(1)

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county,Unnamed: 34
0,NaN,2.5f,NaN,NaN,NaN,NaN,NaN,NaN,"December 6-7, 2023",2023-12-06-07,2023,351.0,NaN,NaN,NaN,NaN,"Keith Duncan, Chief",Division of Budgets,SHOPP,NaN,NaN,NaN,NaN,NaN,NaN,2.5f,NaN,NaN,NaN,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,NaN,NaN,allocation_amendment,NaN,NaN

In [41]:
# full

In [42]:
len((full[full['ppno'].isna()]))

144

In [43]:
(full[full['ppno'].isna()]).groupby(['meeting_year','base_code']).size()

meeting_year  base_code
2021          2.5b          1
2022          2.5b          1
              2.5h          1
              2.5n          1
2023          2.5b          2
              2.5c          1
              2.5f          1
              2.5n          1
              2.8d          1
2024          2.5b          4
              2.5f          3
              2.5s          3
              2.5w          1
              2.8a          1
              2.8b          2
              2.8c          9
              2.8d          8
              2.8v          8
2025          2.5b          7
              2.5c          1
              2.5f          7
              2.5h          2
              2.5n          1
              2.5w          2
              2.8a          9
              2.8b          2
              2.8c         11
              2.8d          9
              2.8v         22
2026          2.5b          5
              2.5e          1
              2.5f          3
              2.5w          1
              2.8a          1
              2.8b          1
              2.8c          7
              2.8d          1
              2.8v          2
dtype: int64

In [44]:
(full[(full['ppno'].isna()) & (full["meeting_year"] == 2025) & (full["base_code"] == "2.8v")]).groupby(['meeting_date','memo_page_start']).size()

meeting_date   memo_page_start
2025-01-30-31  1028.0             1
               1031.0             1
               1036.0             1
2025-03-20-21  1034.0             1
               1037.0             1
2025-05-15-16  1374.0             1
               1377.0             1
               1382.0             1
               1387.0             1
2025-06-26-27  1653.0             1
               1669.0             1
               1676.0             1
               1682.0             1
               1687.0             1
2025-08-14-15  1030.0             1
               1046.0             1
               1048.0             1
2025-10-16-17  1488.0             1
               1491.0             1
               1494.0             1
               1504.0             1
2025-12-04-05  1844.0             1
dtype: int64

In [45]:
# (full[(full["meeting_year"] == 2025) & (full["base_code"] == "2.8v")]).groupby('ppno').size()

In [46]:
### example of project that has multiple entries, one with no PPNO number since the script pulled just the second page of a memo, rather than the first that had the information on it. Check Page 1652 on the CTC meeting book 2025-06-26-2

full[full["ppno"] == "3230"]

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county,Unnamed: 34
604,6566000,2.8v,San Joaquin,Support,NaN,10.0,1C960,04/30/2025 10/31/2025,NaN,2025-06-26-27,2025,1654.0,6 Months 12 Months,CON/CON Support,NaN,3230,NaN,NaN,SHOPP,NaN,NaN,NaN,1.0,NaN,"SHOPP Transportation Management Systems project The Department requests an additional 6 months, from 6 months to 12 months, for the period of project completion for the Construction (CON) phase of the SHOPP Transportation Management Systems project. The Department has experienced unexpected delays in completing construction. The project is located on State Route (SR) 120, in and near Manteca and Lathrop, from Interstate 5 to SR 99. The project proposes to install fiber optic cable as part of the Departmentâ€™s Transportation Management System. Initially, the project received a 6-month extension to resolve a damaged fiber optic line. The contract was awarded in October 2021 and the 36-month deadline to complete Construction Contract Acceptance (CCA) was October 31, 2024. During construction, the contractor ran over and damaged a fiber optic cable while working on the site. This damaged fiber optic line is required to be fully functional with the newly installed project elements. Based on communication with the Contractor and Construction Support team, replacement order and installation of the damaged line was anticipated to take an additional three to six months. The remaining project scope was to be completed concurrently. Since then, the project experienced further delays in late March 2025, primarily due to the absence of factory test results for the fiber optic cables. These test results are essential for evaluating the performance of the installed fiber optic system as part of the projectâ€™s acceptance process. The contractor contacted the fiber optic supplier to request a copy of the factory test results. Unfortunately, the supplier was unable to provide them, as the records were no longer available. After discussions between the Department and the contractor on how to proceed, the testing and inspection will rely on the delivered test results in lieu of the factory test results. The",2.8v.(1),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,NaN,NaN,time_extension,NaN,NaN

In [47]:
(full[(full['ppno'].isna())]).groupby(['meeting_date', 'source']).size()

meeting_date      source
2023-12-06-07     pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf             4
2024-05-16-17     pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf            18
2024-08-15-16     pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf             9
2024-12-05-06     pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf             11
2025-01-30-31     pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf             7
2025-03-20-21     pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf             9
2025-05-15-16     pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf            13
2025-06-26-27     pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf            17
2025-08-14-15     pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf             6
2025-10-16-17     pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf     9
2025-12-04-05     pdfs/2025/2025-12-04-05/2025-12-04-05_complete-book-1858.pdf             5
2026-01-29-30     pdfs/2026/2026-01-29-30/2026-01-29-30_complete-book-1139.pdf             6
2026-03-19-20     pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf             8
2026-05-14-15     pdfs/2026/2026-05-14-15/2026-05-14-15_complete-book-959.pdf              8
30-Jun-21         pdfs/2021/unknown_date/tab-5-2-5b2-combined-a11y.pdf                     1
June 26-27, 2025  pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf        7
June 28-29, 2023  pdfs/2023/2023-06-28-29/2023-06-28-29_tab-112-2-5n-att-a11y.pdf          1
                  pdfs/2023/2023-06-28-29/2023-06-28-29_tab-125-2-5c10-a11y.pdf            1
June 29-30, 2022  pdfs/2022/2022-06-29-30-22/2022-06-29-30-22_tab-89-2-5h.pdf              1
                  pdfs/2022/2022-06-29-30-22/2022-06-29-30-22_tab-94-2-5n-a11y.pdf         1
May 16-17, 2024   pdfs/2024/2024-05-16-17/2024-05-16-17_tab-138-2-8v5-lett.pdf             1
May 18-19, 2022   pdfs/2022/2022-05-18-19-22/2022-05-18-19-22_tab-83-2-5b3-a11y.pdf        1
dtype: int64

In [48]:
len(full)

1270

In [49]:
(full[(full['ppno'].isna()) & (full['meeting_date']=='June 26-27, 2025')])

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county,Unnamed: 34
1245,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1246,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1247,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1248,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1249,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1252,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN
1253,NaN,2.8a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8a.(21),NaN,NaN,NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_tab-163-2-8a21-att-only.pdf,NaN,NaN,time_extension,NaN,NaN

In [50]:
# ppno_null = (full[(full['ppno'].isna())])

In [51]:
# ppno_null.to_csv('ppno_null_checks.csv')

In [52]:
ppno_counts = (full.groupby(['ppno', 'source']).size()).reset_index()

In [53]:
ppno_counts.columns

Index(['ppno', 'source', 0], dtype='object')

In [54]:
ppno_counts = ppno_counts.rename(columns={0:"counts"})

In [55]:
(ppno_counts[ppno_counts['counts']>1]).sort_values('counts')

,ppno,source,counts
1,0044D,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
460,3011R,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
478,3020J,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
479,3020Y,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,2
522,3203,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
527,3215,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,2
534,3276,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
543,3433,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
548,3439,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
609,4353,pdfs/2026/2026-05-14-15/2026-05-14-15_complete-book-959.pdf,2
636,4630,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,2
653,4704,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
672,4785,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,2
714,5059,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
726,5131,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
736,5185,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
757,5370,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
778,5484,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
787,5511,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
801,5625,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
839,6041,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
871,6406,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
919,6960,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
932,6985,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
448,3008C,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
938,7005,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
445,3006G,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,2
426,2992,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
2,0049T,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
27,0226J,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
109,1276,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
114,1302,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,2
229,2024D,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
231,2026H,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,2
234,2027J,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,2
263,2323B,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,2
442,3005R,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
298,2448,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,2
338,2627,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
268,2349,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
349,2645,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
355,2649,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
364,2655,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,2
374,2679X,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
386,2776,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
396,2850,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,2
402,2859C,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
404,2904,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,2
346,2641,pdfs/2025/2025-03-20-21/2025-03-20-21_complete-book-1056.pdf,2
1004,CP033,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,2
564,3546,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,3
697,4998,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,3
359,2653,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,3
227,2022G,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,3
84,0999C,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,3
41,0361M,pdfs/2025/2025-05-15-16/2025-05-15-16_complete-book-1394.pdf,4

In [56]:
# full[full["ppno"] == "5226"]

#### Look at the projects with no null PPNOs

In [57]:
df = (full[~(full['ppno'].isna())])

In [58]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [59]:
len(df)

1126

In [60]:
df.columns

Index(['allocation_amount', 'base_code', 'county', 'department_recommendation',
       'dist_co_rte', 'district', 'ea', 'extended_deadline', 'meeting',
       'meeting_date', 'meeting_year', 'memo_page_start', 'months_requested',
       'phase', 'postmile', 'ppno', 'prepared_by', 'prepared_division',
       'program', 'project_description', 'project_id', 'project_name',
       'project_number', 'reason_for_cost_increase',
       'reason_for_time_extension', 'reference_code', 'requested_amounts',
       'resolution', 'route', 'source', 'subject', 'subject_phase', 'type',
       'vote_county'],
      dtype='object')

In [61]:
df.prepared_division.value_counts()

District 07 â€“ Director             42
Division of Budgets                  38
Division of Financial Programming    34
District 06 â€“ Director             29
Division of Local Assistance         25
District 05 â€“ Director             24
District 01 â€“ Director             22
District 08 â€“ Director             15
District 03 â€“ Director             15
District 04 â€“ Director             13
District 07 - Director               11
District 04 â€“ Director (Acting)    10
District 10 â€“ Director             10
District 05 - Director                7
District 11 â€“ Director              6
District 06 - Director                6
District 09 â€“ Director              6
District 03 - Director                5
District 02 â€“ Director              5
District 12 â€“ Director              3
District 04 - Director (Acting)       3
District 01 - Director                3
District 02 â€“ Director (Acting)     3
District 11 â€“ Director (Acting)     3
District 06 - Director (Acting)       2
District 03 â€“ Director (Acting)     2
District 10 - Director                2
District 02 - Director                2
District 06 â€“ Director (Acting)     2
District 09 - Director                2
District 11 - Director                2
District 08 - Director                2
District 12 - Director                1
Division of Project Management        1
District 04 - Director                1
District 07 â€“ Director (Acting)     1
Name: prepared_division, dtype: int64

In [62]:
df[df['prepared_division']=="Division of Local Assistance"]

,allocation_amount,base_code,county,department_recommendation,dist_co_rte,district,ea,extended_deadline,meeting,meeting_date,meeting_year,memo_page_start,months_requested,phase,postmile,ppno,prepared_by,prepared_division,program,project_description,project_id,project_name,project_number,reason_for_cost_increase,reason_for_time_extension,reference_code,requested_amounts,resolution,route,source,subject,subject_phase,type,vote_county
1,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"December 6-7, 2023",2023-12-06-07,2023,810.0,NaN,NaN,NaN,2675,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for 16 locally-administered Active Transportation Program (ATP) projects from Cycle 2, to deallocate a combined total of $393,000 from all 16 projects to reflect project cost savings, revise the Project Identification Number (Project ID) for three projects, and revise the Project Title for one project?",NaN,2.5w.(4),NaN,NaN,NaN,pdfs/2023/2023-12-06-07/2023-12-06-07_complete-book-1341.pdf,NaN,NaN,allocation_amendment,NaN
59,NaN,2.5c,NaN,NaN,NaN,NaN,NaN,NaN,"May 16-17, 2024",2024-05-16-17,2024,628.0,NaN,NaN,NaN,5156R,"Dee Lam, Chief",Division of Local Assistance,STIP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered State Transportation Improvement Program (STIP) Southwest Boulevard Complete Streets Implementation project (PPNO 5156R), off the State Highway System, in Sonoma County, to revise the recipient?",NaN,2.5c.(6),NaN,"FP-23-88, AMENDING RESOLUTION FP-23-52",NaN,pdfs/2024/2024-05-16-17/2024-05-16-17_complete-book-1547.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
128,NaN,2.5c,NaN,NaN,NaN,NaN,NaN,NaN,"August 15-16, 2024",2024-08-15-16,2024,869.0,NaN,NaN,NaN,2576,"Dee Lam, Chief",Division of Local Assistance,STIP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered State Transportation Improvement Program (STIP) Rio Dell Neighborhood Pedestrian Connectivity Improvements project (PPNO 2576), off the State Highway System, in Humboldt County, to revise the program year for the Right of Way (RW) phase?",NaN,2.5c.(5),NaN,"FP-24-14, AMENDING RESOLUTION FP-23-67",NaN,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
131,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"August 15-16, 2024",2024-08-15-16,2024,882.0,NaN,NaN,NaN,5343,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Reconnecting Union Station to the Historic Cultural Communities of DTLA project (PPNO 5343), off the State Highway System, in Los Angeles County, from Cycle 3A, to rescind the full amount of $5,326,000 from the Construction (CON) phase due to a third-party contract not being awarded within the Timely Use of Funds (TUF) deadline?",NaN,2.5w.(6),NaN,"FATP-2425-02, AMENDING RESOLUTION FATP-2122-09",NaN,pdfs/2024/2024-08-15-16/2024-08-15-16_complete-book-1415.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT FROM CYCLE 3A, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT FROM CYCLE 3A, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
205,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"December 5-6, 2024",2024-12-05-06,2024,686.0,NaN,NaN,NaN,2445A,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Manila Moves Class I Bike Path Project (PPNO 2445A), on the State Highway System, in Humboldt County, to revise the project title and include the request to extend the completion of construction an additional 60 months beyond the 36-month Timely Use of Funds (TUF) deadline?",NaN,2.5w.(3),NaN,"FATP-2425-10, AMENDING RESOLUTION FATP-1920-12",NaN,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, ON THE STATE HIGHWAY","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, ON THE STATE HIGHWAY",allocation_amendment,NaN
219,13500000,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"December 5-6, 2024",2024-12-05-06,2024,812.0,NaN,NaN,NaN,2103D,"Dee Lam, Chief",Division of Local Assistance,TCEP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve a request for an additional $13,500,000 for the Construction (CON) phase of the locally-administered Senate Bill 1 (SB 1) Trade Corridor Enhancement Program (TCEP) 7th Street Grade Separation (East) project (PPNO 2103D), off the State Highway System, in Alameda County?",NaN,2.5s.(7),NaN,TCEP-A-2425-11S,NaN,pdfs/2024/2024-12-05-06/2024-12-05-06_complete-book-989.pdf,"SUPPLEMENTAL FUNDS ALLOCATION FOR THE SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM - 7TH STREET GRADE SEPARATION (EAST) PROJECT, OFF THE STATE HIGHWAY SYSTEM","SUPPLEMENTAL FUNDS ALLOCATION FOR THE SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM - 7TH STREET GRADE SEPARATION (EAST) PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
260,NaN,2.5c,NaN,NaN,NaN,NaN,NaN,NaN,"January 30-31, 2025",2025-01-30-31,2025,499.0,NaN,NaN,NaN,6490,"Dee Lam, Chief",Division of Local Assistance,STIP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered State Transportation Improvement Program (STIP) Meridian and Minaret Roundabout project (PPNO 6490), off the State Highway System, in Mono County, to revise the outcome/outputs?",NaN,2.5c.(5),NaN,"FP-24-60, AMENDING RESOLUTION FP-24-45",NaN,pdfs/2025/2025-01-30-31/2025-01-30-31_complete-book-1061.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
512,NaN,2.5c,NaN,NaN,NaN,NaN,NaN,NaN,"June 26-27, 2025",2025-06-26-27,2025,601.0,NaN,NaN,NaN,5844,"Dee Lam, Chief",Division of Local Assistance,STIP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered State Transportation Improvement Program (STIP) Kammerer Rd Extension (Connector Segment A) project (PPNO 5844), off the State Highway System, in Sacramento County, to revise the description and outputs?",NaN,2.5c.(7),NaN,"FP-24-92, AMENDING RESOLUTION FP-24-12",NaN,pdfs/2025/2025-06-26-27/2025-06-26-27_complete-book-1707.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
627,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"August 14-15, 2025",2025-08-14-15,2025,525.0,NaN,NaN,NaN,1318A,"Dee Lam, Chief",Division of Local Assistance,TCEP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State-Administered Senate Bill 1 (SB 1) Trade Corridor Enhancement Program (TCEP) Southern California Hydrogen Fueling Stations â€“ Phase 1A (Procurement) project (PPNO 1318A), off the State Highway System, in Riverside County, to rescind the full amount of $5,450,000 from the Construction (CON) phase due to the project being canceled?",NaN,2.5s.(10),NaN,"TCEP-A-2526-05, AMENDING RESOLUTION TCEP-A-2425-08",NaN,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM PROJECT â€“ OFF THE STATE HIGHWAY SYSTEM,ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM PROJECT â€“ OFF THE STATE HIGHWAY SYSTEM,allocation_amendment,NaN
628,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"August 14-15, 2025",2025-08-14-15,2025,528.0,NaN,NaN,NaN,1320A,"Dee Lam, Chief",Division of Local Assistance,TCEP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State-Administered Senate Bill 1 (SB 1) Trade Corridor Enhancement Program (TCEP) Southern California Hydrogen Fueling Stations â€“ Phase 3A (Procurement) project (PPNO 1320A), off the State Highway System, in various counties, to rescind the full amount of $10,855,000 from the Construction (CON) phase due to the project being canceled?",NaN,2.5s.(11),NaN,"TCEP-A-2526-07, AMENDING RESOLUTION TCEP-A-2425-08",NaN,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM PROJECT â€“ OFF THE STATE HIGHWAY SYSTEM,ALLOCATION AMENDMENT FOR A STATE-ADMINISTERED SENATE BILL 1 TRADE CORRIDOR ENHANCEMENT PROGRAM PROJECT â€“ OFF THE STATE HIGHWAY SYSTEM,allocation_amendment,NaN
629,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"August 14-15, 2025",2025-08-14-15,2025,534.0,NaN,NaN,NaN,6175,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Campuswide Act ive Transportation Plan project (PPNO 6175), off the State Highway System, in Los Angeles County, to revise the project title?",NaN,2.5w.(6),NaN,"FATP-2526-01, AMENDING RESOLUTION FATP-2425-13",NaN,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT OFF, THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT OFF, THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
630,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"August 14-15, 2025",2025-08-14-15,2025,537.0,NaN,NaN,NaN,2588A,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Turtle Bay to Downtown Gap Completion Project (PPNO 2588A), off the State Highway System, in Shasta County, to include the minor scope change note?",NaN,2.5w.(7),NaN,"FATP-2526-04, AMENDING RESOLUTION FATP-2425-26",NaN,pdfs/2025/2025-08-14-15/2025-08-14-15_complete-book-1059.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
697,NaN,2.5c,NaN,NaN,NaN,NaN,NaN,NaN,"October 16-17, 2025",2025-10-16-17,2025,641.0,NaN,NaN,NaN,3489,"Dee Lam, Chief",Division of Local Assistance,STIP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the State Transportation Improvement Program (STIP) Jamestown Safe, Healthy and Equitable Street Improvements project (PPNO 3489), in Tuolumne County, to revise the recipient, fund type, project ID, program code, and add the advantage phase, postmiles, and route?",NaN,2.5c.(7),NaN,"FP-25-46, AMENDING RESOLUTION FP-24-99",NaN,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT,ALLOCATION AMENDMENT FOR A STATE TRANSPORTATION IMPROVEMENT PROGRAM PROJECT,allocation_amendment,NaN
699,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"October 16-17, 2025",2025-10-16-17,2025,650.0,NaN,NaN,NaN,1276,"Dee Lam, Chief",Division of Local Assistance,LPP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered multi-funded Senate Bill 1 (SB 1) Solutions for Congested Corridors Program (SCCP) and SB 1 Local Partnership Program (LPP) (Formulaic) Mid County Parkway: Ramona Expressway project (PPNO 1276), off the State Highway System, in Riverside County, to revise the outputs?",NaN,2.5s.(8),NaN,"SCCP-A-2526-01, AMENDING RESOLUTION SCCP-A-2425-03",NaN,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED MULTI-FUNDED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM AND SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (FORMULAIC) PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED MULTI-FUNDED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM AND SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (FORMULAIC) PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
700,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"October 16-17, 2025",2025-10-16-17,2025,653.0,NaN,NaN,NaN,5126,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) South Downey Safe Routes to School project (PPNO 5126), off the State Highway System, in Los Angeles County, to split the original allocation between two Budget Authority fiscal years?",NaN,2.5w.(4),NaN,"FATP-2526-06, AMENDING RESOLUTION FATP-2021-08",NaN,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
701,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"October 16-17, 2025",2025-10-16-17,2025,656.0,NaN,NaN,NaN,1531,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Pacific Highway Coastal Rail Trail Airport Connection (PACTAC) project (PPNO 1531), off the State Highway System, in San Diego County, to rescind the full amount of $3,818,000 from the Project Approval & Environmental Document (PA&ED) phase due to cancellation of the project?",NaN,2.5w.(5),NaN,"FATP-2526-07, AMENDING RESOLUTION FATP-2324-28",NaN,pdfs/2025/2025-10-16-17/2025-10-16-17_complete-meeting-book-1512.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
814,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"January 29-30, 2026",2026-01-29-30,2026,525.0,NaN,NaN,NaN,1276,"Dee Lam, Chief",Division of Local Assistance,LPP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered multi-funded Senate Bill 1 (SB 1) Solutions for Congested Corridors Program (SCCP) and SB 1 Local Partnership Program (LPP) (Formulaic) Mid County Parkway: Ramona Expressway project (PPNO 1276), off the State Highway System, in Riverside County, to allow non-proportional spending?",NaN,2.5s.(5),NaN,"SCCP-A-2526-03, AMENDING RESOLUTION SCCP-A-2526-01",NaN,pdfs/2026/2026-01-29-30/2026-01-29-30_complete-book-1139.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED MULTI-FUNDED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM AND SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (FORMULAIC) PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED MULTI-FUNDED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM AND SENATE BILL 1 LOCAL PARTNERSHIP PROGRAM (FORMULAIC) PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
816,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"January 29-30, 2026",2026-01-29-30,2026,534.0,NaN,NaN,NaN,5122,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Boyle Heights Pedestrian Linkages project (PPNO 5122), off the State Highway System, in Los Angeles County, to split the original allocation between two Budget Authority fiscal years?",NaN,2.5w.(4),NaN,"FATP-2526-13, AMENDING RESOLUTION FATP-1819-08",NaN,pdfs/2026/2026-01-29-30/2026-01-29-30_complete-book-1139.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
848,NaN,2.5s,NaN,NaN,NaN,NaN,NaN,NaN,"March 19-20, 2026",2026-03-19-20,2026,793.0,NaN,NaN,NaN,3203,"Dee Lam, Chief",Division of Local Assistance,NaN,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Senate Bill 1 (SB 1) Solutions for Congested Corridors Program (SCCP) Zero Emission Vehicle Infrastructure project (PPNO 3203), off the State Highway System, in Santa Barbara County, to deallocate $168,000 from the Construction (CON) phase to reflect project savings and to revise the project description and outcome/outputs?",NaN,2.5s.(5),NaN,"SCCP-A-2526-07, AMENDING RESOLUTION SCCP-A-2425-04",NaN,pdfs/2026/2026-03-19-20/2026-03-19-20_complete-book-1380.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED SENATE BILL 1 SOLUTIONS FOR CONGESTED CORRIDORS PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN
1256,NaN,2.5w,NaN,NaN,NaN,NaN,NaN,NaN,"August 14-15, 2025","August 14-15, 2025",2025,1.0,NaN,NaN,NaN,2588A,"Dee Lam, Chief",Division of Local Assistance,ATP,NaN,NaN,NaN,NaN,"Should the California Transportation Commission (Commission) approve an allocation amendment for the locally-administered Active Transportation Program (ATP) Turtle Bay to Downtown Gap Completion Project (PPNO 2588A), off the State Highway System, in Shasta County, to revise the project description, outcome/outputs, and include the minor scope change note?",NaN,2.5w.(7),NaN,"FATP-2526-04, AMENDING RESOLUTION FATP-2425-26",NaN,pdfs/2025/2025-08-14-15/2025-08-14-15_tab-49-2-5w7-bi-and-att-a11y.pdf,"ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM","ALLOCATION AMENDMENT FOR A LOCALLY-ADMINISTERED ACTIVE TRANSPORTATION PROGRAM PROJECT, OFF THE STATE HIGHWAY SYSTEM",allocation_amendment,NaN

In [64]:
len(df[df['program']=="LPP"])

20