# Project Analysis

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd 

import numpy as np

import os
import re

import altair as alt

from calitp_data_analysis.sql import to_snakecase
from calitp_data_analysis import calitp_color_palette as cp

from IPython.display import Markdown, HTML, display_html, display
from IPython.core.display import display

In [3]:
from IPython.display import HTML

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
pd.set_option('display.max_colwidth', None)

In [6]:
GCS_PATH = "gs://calitp-analytics-data/data-analyses/project_analysis/"
GCS_PATH_AGENDAS = "gs://calitp-analytics-data/data-analyses/project_analysis/ctc_meeting_books/"

In [7]:
### read in data
full = pd.read_csv(f"{GCS_PATH}ctc_extracted_items_updated.csv")

In [8]:
display(HTML(f'<h2>Summary</h2>'))

In [9]:
 display(HTML(f"Over the last six years, there have been <strong>{len(full)}</strong> items that have appeared in CTC meeting books"))

In [10]:
(full.type.value_counts().reset_index()).rename(columns={"index":"Item Type", "program":"Number of Items"})

              Item Type  type
0        time_extension   857
1  allocation_amendment   411

In [11]:
display(HTML(f'<h3>Item Types</h3>'))

In [12]:
# ((full.groupby(['meeting_year', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items"})

In [13]:
chart = ((alt.Chart(((full.groupby(['meeting_year', 'type']).size()).reset_index().rename(columns={0:"Number of Items"})))
            .mark_bar()
            .encode(
                x=alt.X("type:O", title="Item Type"),
                 y=alt.Y('Number of Items'),
                color=alt.Color("type", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                column='meeting_year'
         )
          .properties(title="Number of Related Items in Analyses", 
                      width=100,
                      height=300)))

In [14]:
chart

alt.Chart(...)

In [15]:
display(HTML(f'<strong>Count of Item Types</strong>'))

In [16]:
(full.meeting_year.value_counts()).reset_index().rename(columns={"index":"Year", "meeting_year":"Number of Items"})

   Year  Number of Items
0  2025              570
1  2024              213
2  2020              175
3  2026              154
4  2023               87
5  2022               46
6  2021               25

In [17]:
display(HTML(f'<strong>Count of Item Types by Subtype</strong>'))

In [18]:
((full.base_code.value_counts()).reset_index()).rename(columns={"index":"Item Code", "base_code":"Number of Items"})

   Item Code  Number of Items
0       2.8a              245
1       2.5e              190
2       2.8c              160
3       2.8d              152
4       2.8v              140
5       2.8b              135
6       2.5d               75
7       2.5s               48
8       2.5b               36
9       2.8i               27
10      2.5c               22
11      2.5w               20
12      2.5f               14
13      2.5h                3
14      2.5n                3

In [19]:
# alt.Chart((((full.groupby(['meeting_year', 'base_code']).size()).reset_index()).rename(columns=({0:"number_of_items"})))).mark_bar(size=70).encode(
#     x=alt.X('meeting_year', title="Meeting Year"),
#     y=alt.Y('number_of_items',),
#     color=alt.Color('base_code')
# ).properties(title="Item Types in Agendas",
#         width=700,
#         height=500)

In [20]:
district = full[full['district']<=12]

In [21]:
# ((district.groupby(['district', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items", "type":"Item Type", "district":"District"})

In [22]:
chart = ((alt.Chart((((district.groupby(['district', 'type']).size()).reset_index()).rename(columns={ 0:"Number of Items", "type":"Item Type", "district":"District"})))
            .mark_bar(size=50)
            .encode(
                x=alt.X("District", title="Caltrans District"),
                 y=alt.Y('Number of Items:Q', title="Number of Items"),
                color=alt.Color("Item Type", title="Caltrans District", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)
                ))
          .properties(title="Number of Items in Analyses by District",
        width=800,
        height=300)))
chart

alt.Chart(...)

In [23]:
full['county'] = full['county'].str.replace(' County', '', regex=False)

In [24]:
chart = ((alt.Chart((full.county.value_counts().reset_index()))
            .mark_bar(size=8)
            .encode(
                x=alt.X("index", title="County"),
                 y=alt.Y('county', title="Number of items"),
                color=alt.Color("index", title="County", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Number of Items in Analyses by County",
        width=1100,
        height=300)))
chart

alt.Chart(...)

In [25]:
display(HTML(f'<strong>Count of Program Types</strong>'))

In [26]:
(full.program.value_counts().reset_index()).rename(columns={"index":"Program", "program":"Number of Items"})

  Program  Number of Items
0   SHOPP              612
1    STIP               82
2    TCEP               28
3     ATP               22
4     LPP               22
5    SCCP                1

In [27]:
# full.sample()

In [28]:
# ((full.groupby(['meeting_year', 'base_code']).size()).reset_index()).rename(columns=({0:"number_of_items"}))

In [29]:
full['prepared_division'] = full['prepared_division'].str.replace(' â€“', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace('-', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace(' (Acting)', '', regex=False)
full['prepared_division'] = full['prepared_division'].str.replace('  ', ' ', regex=False)

In [30]:
# full.prepared_division.value_counts()

In [31]:
display(HTML(f'<strong>Types of Items Presented by the Division of Local Assistance </strong>'))

In [32]:
((full[full['prepared_division']=="Division of Local Assistance"]).base_code.value_counts().reset_index()).rename(columns={"index":"Item Code", "base_code":"Number of Items"})

  Item Code  Number of Items
0      2.5w               14
1      2.5s                8
2      2.5c                6
3      2.8b                2
4      2.8c                1

In [33]:
display(HTML(f'<strong>Types of Items Presented by the Division of Local Assistance </strong>'))

In [34]:
(full[full['prepared_division']=="Division of Local Assistance"]).type.value_counts()

allocation_amendment    28
time_extension           3
Name: type, dtype: int64

In [35]:
display(HTML(f'<strong>Types of items in the LPP Program</strong>'))

In [36]:
(full[full['program']=="LPP"]).type.value_counts()

allocation_amendment    22
Name: type, dtype: int64

In [37]:
# full.columns

In [38]:
display(HTML(f'<h3>Allocation Amendments</h3>'))

In [39]:
full['allocation_amount'] = full['allocation_amount'].str.replace(',', '', regex=False)

In [40]:
amounts = (full[(full['type']=="allocation_amendment") & (full["allocation_amount"].notna())])

In [41]:
amounts['allocation_amount'] = amounts['allocation_amount'].astype(int)

In [99]:
# amounts.groupby('meeting_year').allocation_amount.mean().reset_index()

In [102]:
chart = ((alt.Chart((amounts.groupby('meeting_year').allocation_amount.mean().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('allocation_amount', title="Allocation Amount"),
                color=alt.Color("meeting_year", title="Year", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Average Allocation Amendment Amount by Year",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [98]:
# amounts.groupby(['meeting_year', 'program']).allocation_amount.sum().reset_index()

In [130]:
chart = ((alt.Chart((amounts.groupby(['meeting_year', 'program']).allocation_amount.sum().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('allocation_amount', title="Allocation Amount"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),

                )
          .properties(title="Sum Allocations Amendment Amount by Program",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [ ]:
chart = ((alt.Chart((extension_months.groupby(['meeting_year', 'district', 'program']).months_requested_latest.sum().reset_index()))
            .mark_bar()
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                column='district'
                )
          .properties(title="Total Extension Months by Program",
        width=600,
        # height=300
                     )))
chart

In [45]:
extension = (full[(full['type']=="time_extension")])

In [50]:
# len(extension)

In [47]:
full.columns

Index(['allocation_amount', 'base_code', 'county', 'department_recommendation',
       'dist_co_rte', 'district', 'ea', 'extended_deadline', 'meeting',
       'meeting_date', 'meeting_year', 'memo_page_start', 'months_requested',
       'phase', 'postmile', 'ppno', 'prepared_by', 'prepared_division',
       'program', 'project_description', 'project_id', 'project_name',
       'project_number', 'reason_for_cost_increase',
       'reason_for_time_extension', 'reference_code', 'requested_amounts',
       'resolution', 'route', 'source', 'subject', 'subject_phase', 'type',
       'vote_county', 'Unnamed: 34'],
      dtype='object')

In [67]:
# extension.months_requested.value_counts()

In [68]:
# extension['months_requested_int'] = np.where(
#     extension['months_requested'].str.len() < 10, 
#     extension['months_requested'].str.split().str[0], 
#     extension['months_requested']
# )

In [107]:
# len(extension[extension["months_requested"].isna()])

In [63]:
extension['months_requested_latest'] = extension['months_requested'].str.split().str[-2]

In [77]:
# (extension[extension["months_requested_latest"].isna()]).months_requested.value_counts()

In [79]:
# extension.months_requested_latest.value_counts()

In [75]:
extension['months_requested_latest'] = extension['months_requested_latest'].fillna(extension['months_requested'])

In [80]:
# (extension[~extension["months_requested"].isna()]).sample(10)

In [82]:
extension_months = (extension[~extension["months_requested_latest"].isna()])

In [83]:
extension_months['months_requested_latest'] = extension_months['months_requested_latest'].astype(int)

In [84]:
(extension_months.groupby('meeting_year').months_requested_latest.mean().reset_index())

   meeting_year  months_requested_latest
0          2020                36.188976
1          2021                 9.750000
2          2022                25.333333
3          2023                11.500000
4          2024                11.401961
5          2025                11.953333
6          2026                15.093750

In [114]:
chart = ((alt.Chart((extension_months.groupby('meeting_year').months_requested_latest.mean().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Average Extension Months Requested"),
                color=alt.Color("meeting_year", title="Year", scale=alt.Scale(range = cp.CALITP_SEQUENTIAL_COLORS)
                ))
          .properties(title="Average Number of Months Extension Requested by Year",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [119]:
(extension_months.groupby(['meeting_year','program']).months_requested_latest.sum().reset_index())

    meeting_year program  months_requested_latest
0           2021   SHOPP                       39
1           2022   SHOPP                       76
2           2022    STIP                       96
3           2023     ATP                       36
4           2023    SCCP                        5
5           2023   SHOPP                      250
6           2023    STIP                       44
7           2024   SHOPP                      598
8           2024    STIP                       32
9           2025   SHOPP                     1537
10          2025    STIP                      335
11          2026   SHOPP                      329
12          2026    STIP                       84

In [117]:
chart = ((alt.Chart((extension_months.groupby(['meeting_year','program']).months_requested_latest.sum().reset_index()))
            .mark_bar(size=60)
            .encode(
                x=alt.X("meeting_year:O", title="Meeting Year"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("program", title="Program", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),

                )
          .properties(title="Total Extension Months by Program",
        width=600,
        # height=300
                     )))
chart

alt.Chart(...)

In [135]:
chart = ((alt.Chart((extension_months.groupby('county').months_requested_latest.sum().reset_index()))
            .mark_bar()
            .encode(
                x=alt.X("county", title="County"),
                 y=alt.Y('months_requested_latest', title="Sum of Requested Extension Months"),
                color=alt.Color("county", title="County", scale=alt.Scale(range = cp.CALITP_CATEGORY_BRIGHT_COLORS)),
                )
          .properties(title="Total Extension Months by County",
        width=1100,
        # height=300
                     )))
chart

alt.Chart(...)

In [120]:
# full.groupby(['type', 'base_code']).size()